filebeat.inputs:
- type: container
  paths:
  - '/var/lib/docker/containers/*/*.log'
  processors:
  - add_docker_metadata: ~
output.elasticsearch:
  hosts: ["https://192.168.100.4:9200"]
  username: "elastic"
  password: "mypassword"
  ssl.verification_mode: none
  allow_older_versions: true