version: "2.4"
services:
  filebeat:
    image: filebeat_containers:0.0.1
    build: filebeat
    container_name: filebeat_containers
    hostname: localhost
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=192.168.100.4
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=mypassword
    labels:
      co.elastic.logs/enabled: "false"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"